# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vantage
from vantage.api.network_flow_reports_api import NetworkFlowReportsApi  # noqa: E501
from vantage.rest import ApiException


class TestNetworkFlowReportsApi(unittest.TestCase):
    """NetworkFlowReportsApi unit test stubs"""

    def setUp(self):
        self.api = vantage.api.network_flow_reports_api.NetworkFlowReportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_network_flow_report(self):
        """Test case for create_network_flow_report

        """
        pass

    def test_delete_network_flow_report(self):
        """Test case for delete_network_flow_report

        """
        pass

    def test_get_network_flow_report(self):
        """Test case for get_network_flow_report

        """
        pass

    def test_get_network_flow_reports(self):
        """Test case for get_network_flow_reports

        """
        pass

    def test_update_network_flow_report(self):
        """Test case for update_network_flow_report

        """
        pass


if __name__ == '__main__':
    unittest.main()
