# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vantage
from vantage.models.update_segment import UpdateSegment  # noqa: E501
from vantage.rest import ApiException


class TestUpdateSegment(unittest.TestCase):
    """UpdateSegment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSegment(self):
        """Test UpdateSegment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vantage.models.update_segment.UpdateSegment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
