# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vantage
from vantage.api.report_notifications_api import ReportNotificationsApi  # noqa: E501
from vantage.rest import ApiException


class TestReportNotificationsApi(unittest.TestCase):
    """ReportNotificationsApi unit test stubs"""

    def setUp(self):
        self.api = vantage.api.report_notifications_api.ReportNotificationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_report_notification(self):
        """Test case for create_report_notification

        """
        pass

    def test_delete_report_notification(self):
        """Test case for delete_report_notification

        """
        pass

    def test_get_report_notification(self):
        """Test case for get_report_notification

        """
        pass

    def test_get_report_notifications(self):
        """Test case for get_report_notifications

        """
        pass

    def test_update_report_notification(self):
        """Test case for update_report_notification

        """
        pass


if __name__ == '__main__':
    unittest.main()
