# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vantage
from vantage.models.recommendation_action import RecommendationAction  # noqa: E501
from vantage.rest import ApiException


class TestRecommendationAction(unittest.TestCase):
    """RecommendationAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecommendationAction(self):
        """Test RecommendationAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vantage.models.recommendation_action.RecommendationAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
