# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vantage
from vantage.models.budgets import Budgets  # noqa: E501
from vantage.rest import ApiException


class TestBudgets(unittest.TestCase):
    """Budgets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBudgets(self):
        """Test Budgets"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vantage.models.budgets.Budgets()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
