# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vantage
from vantage.api.saved_filters_api import SavedFiltersApi  # noqa: E501
from vantage.rest import ApiException


class TestSavedFiltersApi(unittest.TestCase):
    """SavedFiltersApi unit test stubs"""

    def setUp(self):
        self.api = vantage.api.saved_filters_api.SavedFiltersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_saved_filter(self):
        """Test case for create_saved_filter

        """
        pass

    def test_delete_saved_filter(self):
        """Test case for delete_saved_filter

        """
        pass

    def test_get_saved_filter(self):
        """Test case for get_saved_filter

        """
        pass

    def test_get_saved_filters(self):
        """Test case for get_saved_filters

        """
        pass

    def test_update_saved_filter(self):
        """Test case for update_saved_filter

        """
        pass


if __name__ == '__main__':
    unittest.main()
