# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vantage
from vantage.api.kubernetes_efficiency_reports_api import KubernetesEfficiencyReportsApi  # noqa: E501
from vantage.rest import ApiException


class TestKubernetesEfficiencyReportsApi(unittest.TestCase):
    """KubernetesEfficiencyReportsApi unit test stubs"""

    def setUp(self):
        self.api = vantage.api.kubernetes_efficiency_reports_api.KubernetesEfficiencyReportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_kubernetes_efficiency_report(self):
        """Test case for create_kubernetes_efficiency_report

        """
        pass

    def test_delete_kubernetes_efficiency_report(self):
        """Test case for delete_kubernetes_efficiency_report

        """
        pass

    def test_get_kubernetes_efficiency_report(self):
        """Test case for get_kubernetes_efficiency_report

        """
        pass

    def test_get_kubernetes_efficiency_reports(self):
        """Test case for get_kubernetes_efficiency_reports

        """
        pass

    def test_update_kubernetes_efficiency_report(self):
        """Test case for update_kubernetes_efficiency_report

        """
        pass


if __name__ == '__main__':
    unittest.main()
