# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vantage
from vantage.api.recommendations_api import RecommendationsApi  # noqa: E501
from vantage.rest import ApiException


class TestRecommendationsApi(unittest.TestCase):
    """RecommendationsApi unit test stubs"""

    def setUp(self):
        self.api = vantage.api.recommendations_api.RecommendationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_recommendation(self):
        """Test case for get_recommendation

        """
        pass

    def test_get_recommendation_resource(self):
        """Test case for get_recommendation_resource

        """
        pass

    def test_get_recommendation_resources(self):
        """Test case for get_recommendation_resources

        """
        pass

    def test_get_recommendations(self):
        """Test case for get_recommendations

        """
        pass


if __name__ == '__main__':
    unittest.main()
