# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vantage
from vantage.api.access_grants_api import AccessGrantsApi  # noqa: E501
from vantage.rest import ApiException


class TestAccessGrantsApi(unittest.TestCase):
    """AccessGrantsApi unit test stubs"""

    def setUp(self):
        self.api = vantage.api.access_grants_api.AccessGrantsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_access_grant(self):
        """Test case for create_access_grant

        """
        pass

    def test_delete_access_grant(self):
        """Test case for delete_access_grant

        """
        pass

    def test_get_access_grant(self):
        """Test case for get_access_grant

        """
        pass

    def test_get_access_grants(self):
        """Test case for get_access_grants

        """
        pass

    def test_update_access_grant(self):
        """Test case for update_access_grant

        """
        pass


if __name__ == '__main__':
    unittest.main()
