# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vantage
from vantage.api.integrations_api import IntegrationsApi  # noqa: E501
from vantage.rest import ApiException


class TestIntegrationsApi(unittest.TestCase):
    """IntegrationsApi unit test stubs"""

    def setUp(self):
        self.api = vantage.api.integrations_api.IntegrationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_azure_integration(self):
        """Test case for create_azure_integration

        """
        pass

    def test_create_custom_provider_integration(self):
        """Test case for create_custom_provider_integration

        """
        pass

    def test_create_gcp_integration(self):
        """Test case for create_gcp_integration

        """
        pass

    def test_create_user_costs_upload_via_csv(self):
        """Test case for create_user_costs_upload_via_csv

        """
        pass

    def test_delete_integration(self):
        """Test case for delete_integration

        """
        pass

    def test_delete_user_costs_upload(self):
        """Test case for delete_user_costs_upload

        """
        pass

    def test_get_integration(self):
        """Test case for get_integration

        """
        pass

    def test_get_integrations(self):
        """Test case for get_integrations

        """
        pass

    def test_get_user_costs_uploads(self):
        """Test case for get_user_costs_uploads

        """
        pass

    def test_update_integration(self):
        """Test case for update_integration

        """
        pass


if __name__ == '__main__':
    unittest.main()
