# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from vantage.api_client import ApiClient


class NetworkFlowReportsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_network_flow_report(self, create_network_flow_report, **kwargs):  # noqa: E501
        """create_network_flow_report  # noqa: E501

        Create a NetworkFlowReport.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_network_flow_report(create_network_flow_report, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CreateNetworkFlowReport create_network_flow_report: (required)
        :return: NetworkFlowReport
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_network_flow_report_with_http_info(create_network_flow_report, **kwargs)  # noqa: E501
        else:
            (data) = self.create_network_flow_report_with_http_info(create_network_flow_report, **kwargs)  # noqa: E501
            return data

    def create_network_flow_report_with_http_info(self, create_network_flow_report, **kwargs):  # noqa: E501
        """create_network_flow_report  # noqa: E501

        Create a NetworkFlowReport.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_network_flow_report_with_http_info(create_network_flow_report, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CreateNetworkFlowReport create_network_flow_report: (required)
        :return: NetworkFlowReport
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['create_network_flow_report']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_network_flow_report" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'create_network_flow_report' is set
        if self.api_client.client_side_validation and ('create_network_flow_report' not in params or
                                                       params['create_network_flow_report'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `create_network_flow_report` when calling `create_network_flow_report`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'create_network_flow_report' in params:
            body_params = params['create_network_flow_report']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/network_flow_reports', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NetworkFlowReport',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_network_flow_report(self, network_flow_report_token, **kwargs):  # noqa: E501
        """delete_network_flow_report  # noqa: E501

        Delete a NetworkFlowReport.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_network_flow_report(network_flow_report_token, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str network_flow_report_token: (required)
        :return: NetworkFlowReport
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_network_flow_report_with_http_info(network_flow_report_token, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_network_flow_report_with_http_info(network_flow_report_token, **kwargs)  # noqa: E501
            return data

    def delete_network_flow_report_with_http_info(self, network_flow_report_token, **kwargs):  # noqa: E501
        """delete_network_flow_report  # noqa: E501

        Delete a NetworkFlowReport.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_network_flow_report_with_http_info(network_flow_report_token, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str network_flow_report_token: (required)
        :return: NetworkFlowReport
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['network_flow_report_token']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_network_flow_report" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'network_flow_report_token' is set
        if self.api_client.client_side_validation and ('network_flow_report_token' not in params or
                                                       params['network_flow_report_token'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `network_flow_report_token` when calling `delete_network_flow_report`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'network_flow_report_token' in params:
            path_params['network_flow_report_token'] = params['network_flow_report_token']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/network_flow_reports/{network_flow_report_token}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NetworkFlowReport',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_network_flow_report(self, network_flow_report_token, **kwargs):  # noqa: E501
        """get_network_flow_report  # noqa: E501

        Return a NetworkFlowReport.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_network_flow_report(network_flow_report_token, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str network_flow_report_token: (required)
        :return: NetworkFlowReport
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_network_flow_report_with_http_info(network_flow_report_token, **kwargs)  # noqa: E501
        else:
            (data) = self.get_network_flow_report_with_http_info(network_flow_report_token, **kwargs)  # noqa: E501
            return data

    def get_network_flow_report_with_http_info(self, network_flow_report_token, **kwargs):  # noqa: E501
        """get_network_flow_report  # noqa: E501

        Return a NetworkFlowReport.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_network_flow_report_with_http_info(network_flow_report_token, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str network_flow_report_token: (required)
        :return: NetworkFlowReport
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['network_flow_report_token']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_network_flow_report" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'network_flow_report_token' is set
        if self.api_client.client_side_validation and ('network_flow_report_token' not in params or
                                                       params['network_flow_report_token'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `network_flow_report_token` when calling `get_network_flow_report`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'network_flow_report_token' in params:
            path_params['network_flow_report_token'] = params['network_flow_report_token']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/network_flow_reports/{network_flow_report_token}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NetworkFlowReport',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_network_flow_reports(self, **kwargs):  # noqa: E501
        """get_network_flow_reports  # noqa: E501

        Return all NetworkFlowReports.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_network_flow_reports(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page: The page of results to return.
        :param int limit: The amount of results to return. The maximum is 1000.
        :return: NetworkFlowReports
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_network_flow_reports_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_network_flow_reports_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_network_flow_reports_with_http_info(self, **kwargs):  # noqa: E501
        """get_network_flow_reports  # noqa: E501

        Return all NetworkFlowReports.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_network_flow_reports_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page: The page of results to return.
        :param int limit: The amount of results to return. The maximum is 1000.
        :return: NetworkFlowReports
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page', 'limit']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_network_flow_reports" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/network_flow_reports', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NetworkFlowReports',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_network_flow_report(self, network_flow_report_token, update_network_flow_report, **kwargs):  # noqa: E501
        """update_network_flow_report  # noqa: E501

        Update a NetworkFlowReport.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_network_flow_report(network_flow_report_token, update_network_flow_report, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str network_flow_report_token: (required)
        :param UpdateNetworkFlowReport update_network_flow_report: (required)
        :return: NetworkFlowReport
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_network_flow_report_with_http_info(network_flow_report_token, update_network_flow_report, **kwargs)  # noqa: E501
        else:
            (data) = self.update_network_flow_report_with_http_info(network_flow_report_token, update_network_flow_report, **kwargs)  # noqa: E501
            return data

    def update_network_flow_report_with_http_info(self, network_flow_report_token, update_network_flow_report, **kwargs):  # noqa: E501
        """update_network_flow_report  # noqa: E501

        Update a NetworkFlowReport.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_network_flow_report_with_http_info(network_flow_report_token, update_network_flow_report, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str network_flow_report_token: (required)
        :param UpdateNetworkFlowReport update_network_flow_report: (required)
        :return: NetworkFlowReport
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['network_flow_report_token', 'update_network_flow_report']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_network_flow_report" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'network_flow_report_token' is set
        if self.api_client.client_side_validation and ('network_flow_report_token' not in params or
                                                       params['network_flow_report_token'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `network_flow_report_token` when calling `update_network_flow_report`")  # noqa: E501
        # verify the required parameter 'update_network_flow_report' is set
        if self.api_client.client_side_validation and ('update_network_flow_report' not in params or
                                                       params['update_network_flow_report'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `update_network_flow_report` when calling `update_network_flow_report`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'network_flow_report_token' in params:
            path_params['network_flow_report_token'] = params['network_flow_report_token']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'update_network_flow_report' in params:
            body_params = params['update_network_flow_report']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/network_flow_reports/{network_flow_report_token}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NetworkFlowReport',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
