# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vantage.configuration import Configuration


class BillingRules(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'object',
        'billing_rules': 'list[BillingRule]'
    }

    attribute_map = {
        'links': 'links',
        'billing_rules': 'billing_rules'
    }

    def __init__(self, links=None, billing_rules=None, _configuration=None):  # noqa: E501
        """BillingRules - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._links = None
        self._billing_rules = None
        self.discriminator = None

        if links is not None:
            self.links = links
        if billing_rules is not None:
            self.billing_rules = billing_rules

    @property
    def links(self):
        """Gets the links of this BillingRules.  # noqa: E501


        :return: The links of this BillingRules.  # noqa: E501
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this BillingRules.


        :param links: The links of this BillingRules.  # noqa: E501
        :type: object
        """

        self._links = links

    @property
    def billing_rules(self):
        """Gets the billing_rules of this BillingRules.  # noqa: E501


        :return: The billing_rules of this BillingRules.  # noqa: E501
        :rtype: list[BillingRule]
        """
        return self._billing_rules

    @billing_rules.setter
    def billing_rules(self, billing_rules):
        """Sets the billing_rules of this BillingRules.


        :param billing_rules: The billing_rules of this BillingRules.  # noqa: E501
        :type: list[BillingRule]
        """

        self._billing_rules = billing_rules

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BillingRules, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BillingRules):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BillingRules):
            return True

        return self.to_dict() != other.to_dict()
