# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vantage.configuration import Configuration


class CreateBudget(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'workspace_token': 'str',
        'cost_report_token': 'str',
        'child_budget_tokens': 'list[str]',
        'periods': 'list[CreateBudgetPeriods]'
    }

    attribute_map = {
        'name': 'name',
        'workspace_token': 'workspace_token',
        'cost_report_token': 'cost_report_token',
        'child_budget_tokens': 'child_budget_tokens',
        'periods': 'periods'
    }

    def __init__(self, name=None, workspace_token=None, cost_report_token=None, child_budget_tokens=None, periods=None, _configuration=None):  # noqa: E501
        """CreateBudget - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._workspace_token = None
        self._cost_report_token = None
        self._child_budget_tokens = None
        self._periods = None
        self.discriminator = None

        self.name = name
        if workspace_token is not None:
            self.workspace_token = workspace_token
        if cost_report_token is not None:
            self.cost_report_token = cost_report_token
        if child_budget_tokens is not None:
            self.child_budget_tokens = child_budget_tokens
        if periods is not None:
            self.periods = periods

    @property
    def name(self):
        """Gets the name of this CreateBudget.  # noqa: E501

        The name of the Budget.  # noqa: E501

        :return: The name of this CreateBudget.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateBudget.

        The name of the Budget.  # noqa: E501

        :param name: The name of this CreateBudget.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def workspace_token(self):
        """Gets the workspace_token of this CreateBudget.  # noqa: E501

        The token of the Workspace to add the Budget to.  # noqa: E501

        :return: The workspace_token of this CreateBudget.  # noqa: E501
        :rtype: str
        """
        return self._workspace_token

    @workspace_token.setter
    def workspace_token(self, workspace_token):
        """Sets the workspace_token of this CreateBudget.

        The token of the Workspace to add the Budget to.  # noqa: E501

        :param workspace_token: The workspace_token of this CreateBudget.  # noqa: E501
        :type: str
        """

        self._workspace_token = workspace_token

    @property
    def cost_report_token(self):
        """Gets the cost_report_token of this CreateBudget.  # noqa: E501

        The CostReport token. Ignored for hierarchical Budgets.  # noqa: E501

        :return: The cost_report_token of this CreateBudget.  # noqa: E501
        :rtype: str
        """
        return self._cost_report_token

    @cost_report_token.setter
    def cost_report_token(self, cost_report_token):
        """Sets the cost_report_token of this CreateBudget.

        The CostReport token. Ignored for hierarchical Budgets.  # noqa: E501

        :param cost_report_token: The cost_report_token of this CreateBudget.  # noqa: E501
        :type: str
        """

        self._cost_report_token = cost_report_token

    @property
    def child_budget_tokens(self):
        """Gets the child_budget_tokens of this CreateBudget.  # noqa: E501

        The tokens of any child Budgets when creating a hierarchical Budget.  # noqa: E501

        :return: The child_budget_tokens of this CreateBudget.  # noqa: E501
        :rtype: list[str]
        """
        return self._child_budget_tokens

    @child_budget_tokens.setter
    def child_budget_tokens(self, child_budget_tokens):
        """Sets the child_budget_tokens of this CreateBudget.

        The tokens of any child Budgets when creating a hierarchical Budget.  # noqa: E501

        :param child_budget_tokens: The child_budget_tokens of this CreateBudget.  # noqa: E501
        :type: list[str]
        """

        self._child_budget_tokens = child_budget_tokens

    @property
    def periods(self):
        """Gets the periods of this CreateBudget.  # noqa: E501

        The periods for the Budget. The start_at and end_at must be iso8601 formatted e.g. YYYY-MM-DD. Ignored for hierarchical Budgets.  # noqa: E501

        :return: The periods of this CreateBudget.  # noqa: E501
        :rtype: list[CreateBudgetPeriods]
        """
        return self._periods

    @periods.setter
    def periods(self, periods):
        """Sets the periods of this CreateBudget.

        The periods for the Budget. The start_at and end_at must be iso8601 formatted e.g. YYYY-MM-DD. Ignored for hierarchical Budgets.  # noqa: E501

        :param periods: The periods of this CreateBudget.  # noqa: E501
        :type: list[CreateBudgetPeriods]
        """

        self._periods = periods

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateBudget, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateBudget):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateBudget):
            return True

        return self.to_dict() != other.to_dict()
