# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vantage.configuration import Configuration


class CreateVirtualTagConfigCostMetric(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'filter': 'str',
        'aggregation': 'CreateVirtualTagConfigCostMetricAggregation'
    }

    attribute_map = {
        'filter': 'filter',
        'aggregation': 'aggregation'
    }

    def __init__(self, filter=None, aggregation=None, _configuration=None):  # noqa: E501
        """CreateVirtualTagConfigCostMetric - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._filter = None
        self._aggregation = None
        self.discriminator = None

        self.filter = filter
        self.aggregation = aggregation

    @property
    def filter(self):
        """Gets the filter of this CreateVirtualTagConfigCostMetric.  # noqa: E501


        :return: The filter of this CreateVirtualTagConfigCostMetric.  # noqa: E501
        :rtype: str
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """Sets the filter of this CreateVirtualTagConfigCostMetric.


        :param filter: The filter of this CreateVirtualTagConfigCostMetric.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and filter is None:
            raise ValueError("Invalid value for `filter`, must not be `None`")  # noqa: E501

        self._filter = filter

    @property
    def aggregation(self):
        """Gets the aggregation of this CreateVirtualTagConfigCostMetric.  # noqa: E501


        :return: The aggregation of this CreateVirtualTagConfigCostMetric.  # noqa: E501
        :rtype: CreateVirtualTagConfigCostMetricAggregation
        """
        return self._aggregation

    @aggregation.setter
    def aggregation(self, aggregation):
        """Sets the aggregation of this CreateVirtualTagConfigCostMetric.


        :param aggregation: The aggregation of this CreateVirtualTagConfigCostMetric.  # noqa: E501
        :type: CreateVirtualTagConfigCostMetricAggregation
        """
        if self._configuration.client_side_validation and aggregation is None:
            raise ValueError("Invalid value for `aggregation`, must not be `None`")  # noqa: E501

        self._aggregation = aggregation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateVirtualTagConfigCostMetric, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateVirtualTagConfigCostMetric):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateVirtualTagConfigCostMetric):
            return True

        return self.to_dict() != other.to_dict()
