# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vantage.configuration import Configuration


class CreateBudgetPeriods(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_at': 'date',
        'end_at': 'date',
        'amount': 'float'
    }

    attribute_map = {
        'start_at': 'start_at',
        'end_at': 'end_at',
        'amount': 'amount'
    }

    def __init__(self, start_at=None, end_at=None, amount=None, _configuration=None):  # noqa: E501
        """CreateBudgetPeriods - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._start_at = None
        self._end_at = None
        self._amount = None
        self.discriminator = None

        self.start_at = start_at
        if end_at is not None:
            self.end_at = end_at
        self.amount = amount

    @property
    def start_at(self):
        """Gets the start_at of this CreateBudgetPeriods.  # noqa: E501

        The start date of the period.  # noqa: E501

        :return: The start_at of this CreateBudgetPeriods.  # noqa: E501
        :rtype: date
        """
        return self._start_at

    @start_at.setter
    def start_at(self, start_at):
        """Sets the start_at of this CreateBudgetPeriods.

        The start date of the period.  # noqa: E501

        :param start_at: The start_at of this CreateBudgetPeriods.  # noqa: E501
        :type: date
        """
        if self._configuration.client_side_validation and start_at is None:
            raise ValueError("Invalid value for `start_at`, must not be `None`")  # noqa: E501

        self._start_at = start_at

    @property
    def end_at(self):
        """Gets the end_at of this CreateBudgetPeriods.  # noqa: E501

        The end date of the period.  # noqa: E501

        :return: The end_at of this CreateBudgetPeriods.  # noqa: E501
        :rtype: date
        """
        return self._end_at

    @end_at.setter
    def end_at(self, end_at):
        """Sets the end_at of this CreateBudgetPeriods.

        The end date of the period.  # noqa: E501

        :param end_at: The end_at of this CreateBudgetPeriods.  # noqa: E501
        :type: date
        """

        self._end_at = end_at

    @property
    def amount(self):
        """Gets the amount of this CreateBudgetPeriods.  # noqa: E501

        The amount of the period.  # noqa: E501

        :return: The amount of this CreateBudgetPeriods.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this CreateBudgetPeriods.

        The amount of the period.  # noqa: E501

        :param amount: The amount of this CreateBudgetPeriods.  # noqa: E501
        :type: float
        """
        if self._configuration.client_side_validation and amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateBudgetPeriods, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateBudgetPeriods):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateBudgetPeriods):
            return True

        return self.to_dict() != other.to_dict()
