# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vantage.configuration import Configuration


class ReportNotification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'token': 'str',
        'title': 'str',
        'cost_report_token': 'str',
        'user_tokens': 'list[str]',
        'recipient_channels': 'list[str]',
        'frequency': 'str',
        'change': 'str'
    }

    attribute_map = {
        'token': 'token',
        'title': 'title',
        'cost_report_token': 'cost_report_token',
        'user_tokens': 'user_tokens',
        'recipient_channels': 'recipient_channels',
        'frequency': 'frequency',
        'change': 'change'
    }

    def __init__(self, token=None, title=None, cost_report_token=None, user_tokens=None, recipient_channels=None, frequency=None, change=None, _configuration=None):  # noqa: E501
        """ReportNotification - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._token = None
        self._title = None
        self._cost_report_token = None
        self._user_tokens = None
        self._recipient_channels = None
        self._frequency = None
        self._change = None
        self.discriminator = None

        if token is not None:
            self.token = token
        if title is not None:
            self.title = title
        if cost_report_token is not None:
            self.cost_report_token = cost_report_token
        if user_tokens is not None:
            self.user_tokens = user_tokens
        if recipient_channels is not None:
            self.recipient_channels = recipient_channels
        if frequency is not None:
            self.frequency = frequency
        if change is not None:
            self.change = change

    @property
    def token(self):
        """Gets the token of this ReportNotification.  # noqa: E501


        :return: The token of this ReportNotification.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this ReportNotification.


        :param token: The token of this ReportNotification.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def title(self):
        """Gets the title of this ReportNotification.  # noqa: E501

        The title of the ReportNotification.  # noqa: E501

        :return: The title of this ReportNotification.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this ReportNotification.

        The title of the ReportNotification.  # noqa: E501

        :param title: The title of this ReportNotification.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def cost_report_token(self):
        """Gets the cost_report_token of this ReportNotification.  # noqa: E501

        The token for a CostReport the ReportNotification is applied to.  # noqa: E501

        :return: The cost_report_token of this ReportNotification.  # noqa: E501
        :rtype: str
        """
        return self._cost_report_token

    @cost_report_token.setter
    def cost_report_token(self, cost_report_token):
        """Sets the cost_report_token of this ReportNotification.

        The token for a CostReport the ReportNotification is applied to.  # noqa: E501

        :param cost_report_token: The cost_report_token of this ReportNotification.  # noqa: E501
        :type: str
        """

        self._cost_report_token = cost_report_token

    @property
    def user_tokens(self):
        """Gets the user_tokens of this ReportNotification.  # noqa: E501

        The Users that receive the notification.  # noqa: E501

        :return: The user_tokens of this ReportNotification.  # noqa: E501
        :rtype: list[str]
        """
        return self._user_tokens

    @user_tokens.setter
    def user_tokens(self, user_tokens):
        """Sets the user_tokens of this ReportNotification.

        The Users that receive the notification.  # noqa: E501

        :param user_tokens: The user_tokens of this ReportNotification.  # noqa: E501
        :type: list[str]
        """

        self._user_tokens = user_tokens

    @property
    def recipient_channels(self):
        """Gets the recipient_channels of this ReportNotification.  # noqa: E501

        The Slack or Microsoft Teams channels that receive the notification.  # noqa: E501

        :return: The recipient_channels of this ReportNotification.  # noqa: E501
        :rtype: list[str]
        """
        return self._recipient_channels

    @recipient_channels.setter
    def recipient_channels(self, recipient_channels):
        """Sets the recipient_channels of this ReportNotification.

        The Slack or Microsoft Teams channels that receive the notification.  # noqa: E501

        :param recipient_channels: The recipient_channels of this ReportNotification.  # noqa: E501
        :type: list[str]
        """

        self._recipient_channels = recipient_channels

    @property
    def frequency(self):
        """Gets the frequency of this ReportNotification.  # noqa: E501

        The frequency the ReportNotification is sent.  # noqa: E501

        :return: The frequency of this ReportNotification.  # noqa: E501
        :rtype: str
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this ReportNotification.

        The frequency the ReportNotification is sent.  # noqa: E501

        :param frequency: The frequency of this ReportNotification.  # noqa: E501
        :type: str
        """
        allowed_values = ["daily", "weekly", "monthly"]  # noqa: E501
        if (self._configuration.client_side_validation and
                frequency not in allowed_values):
            raise ValueError(
                "Invalid value for `frequency` ({0}), must be one of {1}"  # noqa: E501
                .format(frequency, allowed_values)
            )

        self._frequency = frequency

    @property
    def change(self):
        """Gets the change of this ReportNotification.  # noqa: E501

        The type of change the ReportNotification is tracking.  # noqa: E501

        :return: The change of this ReportNotification.  # noqa: E501
        :rtype: str
        """
        return self._change

    @change.setter
    def change(self, change):
        """Sets the change of this ReportNotification.

        The type of change the ReportNotification is tracking.  # noqa: E501

        :param change: The change of this ReportNotification.  # noqa: E501
        :type: str
        """
        allowed_values = ["percentage", "dollars"]  # noqa: E501
        if (self._configuration.client_side_validation and
                change not in allowed_values):
            raise ValueError(
                "Invalid value for `change` ({0}), must be one of {1}"  # noqa: E501
                .format(change, allowed_values)
            )

        self._change = change

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReportNotification, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReportNotification):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ReportNotification):
            return True

        return self.to_dict() != other.to_dict()
