# coding: utf-8

"""
    Vantage

    Vantage API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@vantage.sh
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vantage.configuration import Configuration


class UpdateDashboard(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'widgets': 'list[CreateDashboardWidgets]',
        'saved_filter_tokens': 'list[str]',
        'date_bin': 'str',
        'date_interval': 'str',
        'start_date': 'str',
        'end_date': 'str',
        'workspace_token': 'str'
    }

    attribute_map = {
        'title': 'title',
        'widgets': 'widgets',
        'saved_filter_tokens': 'saved_filter_tokens',
        'date_bin': 'date_bin',
        'date_interval': 'date_interval',
        'start_date': 'start_date',
        'end_date': 'end_date',
        'workspace_token': 'workspace_token'
    }

    def __init__(self, title=None, widgets=None, saved_filter_tokens=None, date_bin=None, date_interval=None, start_date=None, end_date=None, workspace_token=None, _configuration=None):  # noqa: E501
        """UpdateDashboard - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._title = None
        self._widgets = None
        self._saved_filter_tokens = None
        self._date_bin = None
        self._date_interval = None
        self._start_date = None
        self._end_date = None
        self._workspace_token = None
        self.discriminator = None

        if title is not None:
            self.title = title
        if widgets is not None:
            self.widgets = widgets
        if saved_filter_tokens is not None:
            self.saved_filter_tokens = saved_filter_tokens
        if date_bin is not None:
            self.date_bin = date_bin
        if date_interval is not None:
            self.date_interval = date_interval
        if start_date is not None:
            self.start_date = start_date
        self.end_date = end_date
        if workspace_token is not None:
            self.workspace_token = workspace_token

    @property
    def title(self):
        """Gets the title of this UpdateDashboard.  # noqa: E501

        The title of the Dashboard.  # noqa: E501

        :return: The title of this UpdateDashboard.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this UpdateDashboard.

        The title of the Dashboard.  # noqa: E501

        :param title: The title of this UpdateDashboard.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def widgets(self):
        """Gets the widgets of this UpdateDashboard.  # noqa: E501

        The widgets to add to the Dashboard. Currently supports CostReport, ResourceReport, KubernetesEfficiencyReport, and FinancialCommitmentReport.  # noqa: E501

        :return: The widgets of this UpdateDashboard.  # noqa: E501
        :rtype: list[CreateDashboardWidgets]
        """
        return self._widgets

    @widgets.setter
    def widgets(self, widgets):
        """Sets the widgets of this UpdateDashboard.

        The widgets to add to the Dashboard. Currently supports CostReport, ResourceReport, KubernetesEfficiencyReport, and FinancialCommitmentReport.  # noqa: E501

        :param widgets: The widgets of this UpdateDashboard.  # noqa: E501
        :type: list[CreateDashboardWidgets]
        """

        self._widgets = widgets

    @property
    def saved_filter_tokens(self):
        """Gets the saved_filter_tokens of this UpdateDashboard.  # noqa: E501

        The tokens of the Saved Filters used in the Dashboard.  # noqa: E501

        :return: The saved_filter_tokens of this UpdateDashboard.  # noqa: E501
        :rtype: list[str]
        """
        return self._saved_filter_tokens

    @saved_filter_tokens.setter
    def saved_filter_tokens(self, saved_filter_tokens):
        """Sets the saved_filter_tokens of this UpdateDashboard.

        The tokens of the Saved Filters used in the Dashboard.  # noqa: E501

        :param saved_filter_tokens: The saved_filter_tokens of this UpdateDashboard.  # noqa: E501
        :type: list[str]
        """

        self._saved_filter_tokens = saved_filter_tokens

    @property
    def date_bin(self):
        """Gets the date_bin of this UpdateDashboard.  # noqa: E501

        Determines how to group costs in the Dashboard.  # noqa: E501

        :return: The date_bin of this UpdateDashboard.  # noqa: E501
        :rtype: str
        """
        return self._date_bin

    @date_bin.setter
    def date_bin(self, date_bin):
        """Sets the date_bin of this UpdateDashboard.

        Determines how to group costs in the Dashboard.  # noqa: E501

        :param date_bin: The date_bin of this UpdateDashboard.  # noqa: E501
        :type: str
        """
        allowed_values = ["cumulative", "day", "week", "month"]  # noqa: E501
        if (self._configuration.client_side_validation and
                date_bin not in allowed_values):
            raise ValueError(
                "Invalid value for `date_bin` ({0}), must be one of {1}"  # noqa: E501
                .format(date_bin, allowed_values)
            )

        self._date_bin = date_bin

    @property
    def date_interval(self):
        """Gets the date_interval of this UpdateDashboard.  # noqa: E501

        Determines the date range in the Dashboard. Incompatible with 'start_date' and 'end_date' parameters.  # noqa: E501

        :return: The date_interval of this UpdateDashboard.  # noqa: E501
        :rtype: str
        """
        return self._date_interval

    @date_interval.setter
    def date_interval(self, date_interval):
        """Sets the date_interval of this UpdateDashboard.

        Determines the date range in the Dashboard. Incompatible with 'start_date' and 'end_date' parameters.  # noqa: E501

        :param date_interval: The date_interval of this UpdateDashboard.  # noqa: E501
        :type: str
        """
        allowed_values = ["this_month", "last_7_days", "last_30_days", "last_month", "last_3_months", "last_6_months", "custom", "last_12_months", "last_24_months", "last_36_months", "next_month", "next_3_months", "next_6_months", "next_12_months", "year_to_date", "last_3_days"]  # noqa: E501
        if (self._configuration.client_side_validation and
                date_interval not in allowed_values):
            raise ValueError(
                "Invalid value for `date_interval` ({0}), must be one of {1}"  # noqa: E501
                .format(date_interval, allowed_values)
            )

        self._date_interval = date_interval

    @property
    def start_date(self):
        """Gets the start_date of this UpdateDashboard.  # noqa: E501

        The start date for the date range for costs in the Dashboard. ISO 8601 Formatted. Incompatible with 'date_interval' parameter.  # noqa: E501

        :return: The start_date of this UpdateDashboard.  # noqa: E501
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this UpdateDashboard.

        The start date for the date range for costs in the Dashboard. ISO 8601 Formatted. Incompatible with 'date_interval' parameter.  # noqa: E501

        :param start_date: The start_date of this UpdateDashboard.  # noqa: E501
        :type: str
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this UpdateDashboard.  # noqa: E501

        The end date for the date range for costs in the Dashboard. ISO 8601 Formatted. Incompatible with 'date_interval' parameter.  # noqa: E501

        :return: The end_date of this UpdateDashboard.  # noqa: E501
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this UpdateDashboard.

        The end date for the date range for costs in the Dashboard. ISO 8601 Formatted. Incompatible with 'date_interval' parameter.  # noqa: E501

        :param end_date: The end_date of this UpdateDashboard.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and end_date is None:
            raise ValueError("Invalid value for `end_date`, must not be `None`")  # noqa: E501

        self._end_date = end_date

    @property
    def workspace_token(self):
        """Gets the workspace_token of this UpdateDashboard.  # noqa: E501

        The token of the Workspace the Dashboard belongs to. Required if the API token is associated with multiple Workspaces.  # noqa: E501

        :return: The workspace_token of this UpdateDashboard.  # noqa: E501
        :rtype: str
        """
        return self._workspace_token

    @workspace_token.setter
    def workspace_token(self, workspace_token):
        """Sets the workspace_token of this UpdateDashboard.

        The token of the Workspace the Dashboard belongs to. Required if the API token is associated with multiple Workspaces.  # noqa: E501

        :param workspace_token: The workspace_token of this UpdateDashboard.  # noqa: E501
        :type: str
        """

        self._workspace_token = workspace_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateDashboard, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateDashboard):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateDashboard):
            return True

        return self.to_dict() != other.to_dict()
