from enum import Enum


class GetRecommendationsCategory(str, Enum):
    AWS_IP_UNATTACHED_RECOMMENDER = "aws_ip_unattached_recommender"
    AWS_STRANDED_WORKSPACE_RECOMMENDER = "aws_stranded_workspace_recommender"
    AWS_UNATTACHED_VOLUME_RECOMMENDER = "aws_unattached_volume_recommender"
    AWS_UNUSED_WORKSPACE_RECOMMENDER = "aws_unused_workspace_recommender"
    AZURE_BLOB_STORAGE_RESERVED_INSTANCES_RECOMMENDER = "azure_blob_storage_reserved_instances_recommender"
    AZURE_COMPUTE_SAVINGS_RECOMMENDER = "azure_compute_savings_recommender"
    AZURE_FILES_RESERVED_INSTANCES_RECOMMENDER = "azure_files_reserved_instances_recommender"
    AZURE_RIGHTSIZING_RECOMMENDER = "azure_rightsizing_recommender"
    AZURE_SQL_PAAS_DB_RESERVED_INSTANCES_RECOMMENDER = "azure_sql_paas_db_reserved_instances_recommender"
    AZ_COMPUTE_RESERVED_INSTANCES = "az_compute_reserved_instances"
    AZ_COMPUTE_RESERVED_INSTANCES_APP_SERVICE = "az_compute_reserved_instances_app_service"
    AZ_COMPUTE_RESERVED_INSTANCES_COSMOS = "az_compute_reserved_instances_cosmos"
    AZ_COMPUTE_RESERVED_INSTANCES_SQL = "az_compute_reserved_instances_sql"
    AZ_DISKS_UNATTACHED = "az_disks_unattached"
    CLOUDFRONT_CLOUDFLARE = "cloudfront_cloudflare"
    CW_LOG_RETENTION_POLICY = "cw_log_retention_policy"
    DATADOG_FINANCIAL_COMMITMENTS = "datadog_financial_commitments"
    DYNAMODB_RESERVED_CAPACITY_RECOMMENDER = "dynamodb_reserved_capacity_recommender"
    EBS_COMPUTE_OPTIMIZER_RECOMMENDER = "ebs_compute_optimizer_recommender"
    EBS_GP2_TO_GP3 = "ebs_gp2_to_gp3"
    EBS_UNATTACHED_VOLUME = "ebs_unattached_volume"
    EC2_GENERATIONAL_UPGRADES = "ec2_generational_upgrades"
    EC2_RIGHTSIZING_RECOMMENDER = "ec2_rightsizing_recommender"
    EC2_SNAPSHOT_RECOMMENDER = "ec2_snapshot_recommender"
    ECS_COMPUTE_OPTIMIZER_RECOMMENDER = "ecs_compute_optimizer_recommender"
    ELASTICACHE_RESERVED_INSTANCES = "elasticache_reserved_instances"
    ELASTIC_SEARCH_RESERVED_INSTANCES = "elastic_search_reserved_instances"
    ES_GENERATIONAL_UPGRADES = "es_generational_upgrades"
    GCP_COMPUTE_COMMITMENT_RECOMMENDER = "gcp_compute_commitment_recommender"
    GCP_COMPUTE_RIGHTSIZING_RECOMMENDER = "gcp_compute_rightsizing_recommender"
    IP_UNATTACHED = "ip_unattached"
    KUBERNETES_RECOMMENDER = "kubernetes_recommender"
    LAMBDA_COMPUTE_OPTIMIZER_RECOMMENDER = "lambda_compute_optimizer_recommender"
    RDS_COMPUTE_OPTIMIZER_RECOMMENDER = "rds_compute_optimizer_recommender"
    RDS_GENERATIONAL_UPGRADES = "rds_generational_upgrades"
    RDS_RESERVED_INSTANCES = "rds_reserved_instances"
    REDSHIFT_RESERVED_INSTANCES = "redshift_reserved_instances"
    S3_BUCKET_INTELLIGENT_TIERING = "s3_bucket_intelligent_tiering"
    S3_CLOUDFLARE = "s3_cloudflare"
    SAVINGS_PLAN = "savings_plan"
    UNUSED_FINANCIAL_COMMITMENTS = "unused_financial_commitments"
    WORKSPACE_STRANDED = "workspace_stranded"
    WORKSPACE_UNUSED = "workspace_unused"

    def __str__(self) -> str:
        return str(self.value)
